services:
  mongodb:
    image: mongo:7.0
    container_name: shelf-net-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: shelfnet
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret

volumes:
  mongo_data: